dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt-get install -y libspatialindex-dev libgeos-dev gdal-bin

install:
  - python setup.py develop
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov pysim5g --cov-report term-missing
after_success:
  - coveralls
